{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 AWSTemplateFormatVersion: "2010-09-09"\
Transform: "AWS::Serverless-2016-10-31"\
Description: CD Demo Lambda\
Resources:\
  CDDemoLambda1:\
    Type: "AWS::Serverless::Function"\
    Properties:\
      FunctionName: LF2-search-photos\
      Handler: lambda_function.lambda_handler\
      Runtime: python3.8\
      CodeUri: ./search-photos\
      Description: "Lambda function for CD Demo"\
      MemorySize: 128\
      Timeout: 30\
      Role: "arn:aws:iam::766368028132:role/service-role/s3-index-photos-role"\
      Environment:\
        Variables:\
          REGION: us-east-1\
  CDDemoLambda2:\
    Type: "AWS::Serverless::Function"\
    Properties:\
      FunctionName: LF1-index-photos\
      Handler: lambda_function.lambda_handler\
      Runtime: python3.7\
      CodeUri: ./index-photos\
      Description: "Lambda function for CD Demo"\
      MemorySize: 128\
      Timeout: 30\
      Role: "arn:aws:iam::766368028132:role/service-role/s3-index-photos-role"\
      Environment:\
        Variables:\
          REGION: us-east-1}